version : "3.8"
services:
  redis:
    image: redis
    container_name: rental-redis
    hostname: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
     - mynet
  database:
    image: mysql:latest
    restart: always
    container_name: rental-mysql
    environment:
      MYSQL_DATABASE: rental
      MYSQL_ROOT_PASSWORD: 0000
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mynet
  springbootapp:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - database
    container_name: rental-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/rental?serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 0000
    networks:
      - mynet
networks:
  mynet:
    driver: bridge
